export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_INGREDIENT = "SET_INGREDIENT";

export const INGREDIENT_SEARCH = {
    SET_LAST_SEARCH_NAME: "INGREDIENTS_SEARCH.SET_LAST_SEARCH_NAME",
    SET_LAST_CLICKED: "INGREDIENTS_SEARCH.SET_LAST_CLICKED",
    SET_LAST_SEARCH_RESULT: "INGREDIENTS_SEARCH.SET_LAST_SEARCH_RESULT"
};