delete from ingredient where id > 0;

insert into ingredient (name, kcal, fat, salt, carbohydrate, roughage, sugar, protein) values('Cebula zwyczajna', 39, 0, 4, 9, 1.7, 4.2, 1.1);
insert into ingredient (name, kcal, fat, salt, carbohydrate, roughage, sugar, protein) values('Chleb', 264, 3.2, 0.491, 49, 2.7, 5, 9);
insert into ingredient (name, kcal, fat, salt, carbohydrate, roughage, sugar, protein) values('Jabłko', 52, 0, 0.001, 14, 2.4, 1, 0);
insert into ingredient (name, kcal, fat, salt, carbohydrate, roughage, sugar, protein) values('Cytryna zwyczajna', 28, 0, 0.002, 9, 2.8, 2.5, 1.1);
insert into ingredient (name, kcal, fat, salt, carbohydrate, roughage, sugar, protein) values('Kapusta głowiasta', 24, 0, 0.018, 6, 2.5, 3.2, 1.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pieczarka', 21, 2.7, 0.4, 2.6, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ogórek', 14, 0.7, 0.1, 2.4, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kapusta biala mloda', 43, 1.7, 0.2, 7.4, 2.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kapusta pak choi', 13, 1.5, 0.2, 2.2, 1, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kapusta wloska', 43, 3.3, 0.4, 5.2, 2.6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kapusta pekinska', 16, 1.2, 0.2, 1.3, 1.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kapusta biala', 33, 1.7, 0.2, 4.9, 2.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ogórek konserwowy w zalewie musztardowej kozacki', 63, 0.8, 0.4, 14, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ogórek gruntowy', 14, 0.7, 0.1, 2.4, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ogórek kiszony', 12, 1, 0.1, 1.4, 0.5, 1.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ogórek konserwowy', 23, 0.4, 0.1, 4.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ogórek malosolny', 11, 0.3, 0.2, 2.3, 1.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Szklanka Jogurt naturalny', 60, 4.3, 2, 6.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Jogurt naturalny', 60, 4.3, 2, 6.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt typu skyr naturalny', 64, 12, 0, 4.1, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt kokosowe naturalny planton bez cukru', 87, 0.8, 6.4, 6.4, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt kokosowe naturalny planton z cukrem', 95, 0.9, 5.3, 11, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt naturalny activia', 69, 4.5, 3.4, 5.1, 0, 0.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Jugortu owczego naturalny', 104, 5.9, 6.8, 4.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt sojowego naturalny', 50, 4.7, 2.6, 1.6, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt pitnego do picia naturalny', 50, 3.4, 2, 4.6, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Jogurt kozi', 79, 5.6, 6, 2.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt naturalny do picia bez laktozy', 50, 3.4, 1.9, 3.9, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt naturalny 0%', 49, 5.2, 0.2, 6.7, 0, 0.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt sojowy naturalny', 50, 4.7, 2.6, 1.6, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jogurt naturalny gesty', 58, 3.3, 2.8, 4.9, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Jogurt typu greckiego light', 74, 4.4, 3.5, 6.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serwatki', 25, 0.8, 0.1, 5.1, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser topiony gouda do smarowania serissimo', 253, 10, 21, 6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serek topiony koziego', 266, 13, 22, 4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser smażony z kminkiem', 80, 16, 0.5, 4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser cambozola', 427, 14, 41, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Deser monte crunchy', 214, 3.4, 13.4, 19.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Deser o smaku czekoladowo waniliowym z niespodzianka', 136, 3.1, 5.6, 18, 0.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Deser o smaku czekoladowym z bita smietanka', 102, 2.2, 2.6, 17.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Deser satino panna cotta', 157, 3, 8.6, 17, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser cheestring twister', 314, 24, 23, 2.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser forte classico', 350, 33, 26, 0, 0, 1.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serce czekoladowe bez cukru sojowa alternatywa dla Mleko', 567, 14.6, 47, 26.3, 6.4, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serce karczocha w zalewie naturalnej', 31, 1.4, 0.4, 5.5, 0, 3.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serdelek z kurczat', 216, 12.3, 16.9, 3.6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serek chudy miss talia 0', 58, 9.2, 0, 5.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serek naturalny bieluch lekki', 81, 9, 3, 4.5, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serek wiejski z miodem', 140, 8.7, 4, 17.4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serek wiejski ze szczypiorkiem', 97, 11, 5, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser ementaler pelnotlusty', 383, 28.2, 29.7, 0.1, 0, 2.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser gryfickiego', 329, 26, 25, 0.5, 0, 2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser poltwardego zielonego pokusa', 332, 25.1, 25.3, 0.1, 0, 1.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serka danonki o smaku truskawkowym', 107, 6.4, 2.9, 13.8, 1.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serka homogenizowanego naturalny', 114, 8.2, 7, 4.5, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Sztuka serca palmy rdzen w zalewie wodnej', 16, 0, 0.6, 1.3, 0, 0.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser kremowego topiony w kubku z serem gouda', 255, 9.8, 21, 6.6, 0, 1.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serka wiejskiego ze szczypiorkiem', 97, 11, 5, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser smażony', 166, 20.5, 7.5, 4.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serek rondele z orzechami', 305, 6.4, 30, 2.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('3 sztuki serca palmy rdzen w zalewie wodnej', 16, 0, 0.6, 1.3, 0, 0.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Deser z serem o smaku lodow w rozku', 371, 3.2, 25, 35, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serdelek bydgoski', 323, 11, 31.5, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serek brie', 332, 19.4, 28, 0.2, 0, 2.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Deser sojowy z figami', 76, 3.6, 2, 11, 1.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serce z indyka', 113, 17.1, 4.8, 0.4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Serce z kurczaka', 153, 15.5, 9.3, 0.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Serek wiejski naturalny', 97, 11, 5, 2, 0, 0.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser koryciński', 280, 18.4, 22.9, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kulka serowa przekaska piwosza', 318, 25, 24, 0.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser bez laktozy sokol', 334, 25, 26, 0, 0, 1.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Sea camembert o smaku wędzonym', 356, 18, 31, 1.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser feta bez laktozy', 270, 16.4, 22.5, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser gorgonzola', 356, 19.4, 31.2, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser gouda zielone pesto', 380, 22.9, 32.1, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ser kaszkawal', 325, 25, 25, 0.1, 0, 2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser krolewskiego', 359, 27, 27, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser mozzarella podpuszczkowego niedojrzewajacego', 278, 24, 20, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ser owczego manouri', 275, 16, 23, 1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Majonez', 663, 1, 71.8, 3.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Majonez bez glutenu i bez soli', 750, 1.6, 81.7, 2.1, 0, 0.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Majonez lekki', 280, 0.6, 27, 9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Truskawek', 33, 0.7, 0.4, 5.8, 1.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomidora', 19, 0.9, 0.2, 2.9, 1.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Sredni pomidor', 19, 0.9, 0.2, 2.9, 1.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomidor bawole serce', 19, 0.9, 0.2, 2.9, 1.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomidor koktajlowy w Olej', 170, 3.5, 13, 6.4, 6.7, 1.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomidor sliwkowy rzymski zolty', 19, 0.9, 0.2, 2.9, 1.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomidor koktajlowy', 19, 0.9, 0.2, 2.9, 1.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomidor kumato', 20, 0.7, 0.3, 3.1, 1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Pomidor pomaranczowy', 16, 1.2, 0.2, 3.2, 0.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Pomidor zapiekany z papryczka w uleju', 147, 3, 10, 11.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pierś z kurczaka', 98, 21.5, 1.3, 0, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Gotowana pierś z kurczaka', 151, 32.9, 2, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Wedzona pierś z kurczaka', 107, 23, 0.5, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Śmietana sojowa', 99, 2.2, 9.2, 1.5, 0.6, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Śmietana 30%', 291, 2.2, 30, 3.1, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Śmietana 12%', 134, 2.6, 12, 3.9, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Śmietana 18%', 186, 2.4, 18, 3.6, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron z zupy blyskawicznej 2', 453, 9, 17, 65, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron lasagne', 350, 11.5, 1.5, 72.7, 2.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron lasagne ugotowany', 138, 4.5, 0.6, 28.7, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron chiński sojowego', 342, 0.5, 0, 84.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron z Ryż czarnego', 347, 6.9, 2.8, 72.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron z sosem pieczarkowym danie w 5 minut', 78, 2.1, 1.9, 12.9, 0.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron bezglutenowego', 357, 4.5, 2.1, 80.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Makaron fusilli z pszenicy plaskurka', 348, 13.1, 1, 68.7, 6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron gryczanego swiderki', 349, 14.4, 3, 66, 3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron nitki', 349, 12.2, 1.7, 71.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron owsianego', 360, 15, 5.3, 75.2, 7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron owsianego ugotowanego', 144, 6, 2.1, 30.1, 2.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron penne', 345, 15.2, 1.3, 68, 6.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron pelnoziarnistego z 5 zboz', 351, 14.4, 2.5, 63.8, 7.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron swiderki', 345, 15.2, 1.3, 68, 6.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron rurki', 350, 12, 1.5, 72.1, 3.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron tagliatelle mosse', 351, 13, 1.4, 70, 3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron w formie Ryż', 350, 12, 1.5, 72.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron w ksztalcie literek pasta kids', 350, 12, 1.5, 72.1, 1.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron lazanki', 336, 13.5, 0.3, 69.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron zytniego swiderki', 340, 10, 2.3, 70, 7.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron ryzowego', 97, 1.8, 0.8, 22.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron chiński sojowego', 86, 0.1, 0, 21.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron gryczanego swiderki', 140, 5.8, 1.2, 26.4, 1.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron jajecznego tagliatelle', 146, 5.7, 1.6, 27.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron nitki', 140, 4.9, 0.7, 28.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron pelnoziarnistego z 5 zboz', 163, 6.7, 1.2, 29.7, 3.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron swiderki', 110, 4.9, 0.4, 21.8, 2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron razowego spaghetti', 154, 5.7, 1.1, 28.9, 3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron spaghetti z pomidorem i szpinakiem', 132, 4.5, 0.5, 27.4, 1.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron w ksztalcie literek pasta kids', 159, 5.5, 0.7, 32.8, 0.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ugotowany Makaron lazanki', 190, 6.6, 0.7, 38, 2.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowany Makaron zytniego muszle', 195, 5, 0.8, 41.8, 4.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowanego pelnoziarnistego Makaron jeczmiennego kolanka', 155, 4.3, 1, 32.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron gryczanego', 348, 14.7, 0.9, 70.5, 5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron jajecznego tagliatelle', 277, 10.9, 3, 51.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron pelnoziarnistego spaghetti', 345, 15.2, 1.3, 68, 6.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron karobowego', 370, 10.7, 2.7, 75.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron konjac fettuccine', 6, 0, 0, 0.5, 4.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron konjac noodles', 6, 0, 0, 0.5, 4.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron konjac spaghetti', 6, 0, 0, 0.5, 4.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron lasagne konjac', 7, 0, 0, 0, 3.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron na patelnie z sosem bolognese', 131, 4.6, 5.3, 15.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron nitki z brazowego Ryż', 362, 6.6, 0.9, 81.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron pelnoziarnistego gniazda wstazki 1', 340, 15, 3.2, 58, 9.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Makaron po bolonsku z wolowina quicker dzienna racja zestaw 1', 107, 4.4, 2, 17, 1.4, 1.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron razowego spaghetti', 354, 13, 2.5, 66.5, 7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Makaron ryzowego', 365, 6.8, 0.7, 83, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada kokosowa', 599, 4, 44, 44, 4, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna dove caramel', 485, 5, 24.2, 61.3, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada mleczna milka i oreo', 550, 5.6, 33, 56, 1.6, 0.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna z krakersami milka tuc', 525, 6.4, 28, 60, 1.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada mleczna z nadzieniem mlecznym i zbozami kinder country', 561, 8.6, 33.8, 54.9, 0, 0.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada 70 lacasa', 583, 6.1, 47.1, 33.6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna do picia w formie lyzki', 530, 6.6, 29.5, 58.5, 1.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values(' Czekolada nadziewanej z maslem orzechowym', 553, 8.4, 37, 44, 0, 0.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada mleczna milka', 530, 6.3, 29, 59, 1.8, 0.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada do picia na patyku', 614, 4.9, 45.9, 45.3, 1.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Mleczna Czekolada milka vanilla cream', 455, 4.3, 29, 43, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada milka bubbly alpine milk', 535, 6.4, 30.5, 57.5, 1.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada gorzka malinowa', 510, 3.8, 29.5, 55, 4.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada lindt hello caramel brownie', 549, 6.6, 35, 51, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values(' Czekolada mleczna bez laktozy', 551, 9.2, 34, 51, 2.1, 0.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values(' Czekolada mleczna milka', 530, 6.3, 29, 59, 1.8, 0.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values(' Czekolada mleczna o smaku creme brulee 1', 520, 5.1, 29.1, 58.6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values(' Czekolada mleczna z ciasteczkami orzechowojaglanymi', 431, 16.4, 31.6, 16.5, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values(' Czekolada mleczna z galaretka wawel', 516, 5.1, 28, 60, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values(' Czekolada z borowka', 500, 6, 31, 50, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada gorzka malinowa', 510, 3.8, 29.5, 55, 4.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada mleczna', 530, 6, 30, 58, 2.5, 0.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada mleczna bez laktozy', 551, 9.2, 34, 51, 2.1, 0.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna o smaku creme brulee 1', 520, 5.1, 29.1, 58.6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada mleczna z ciasteczkami orzechowojaglanymi', 431, 16.4, 31.6, 16.5, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna z galaretka wawel', 516, 5.1, 28, 60, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna z migdalami', 515, 8.9, 30, 50, 2.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada slodzonej ksylitolem alternatywna dla mleczna Czekolada', 567, 14.6, 47, 26.3, 6.4, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada z karobem carobella', 554, 7.1, 36.7, 47.8, 4.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna do picia po przygotowaniu', 125, 3.7, 6.6, 11.7, 0.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada lindt hello caramel brownie', 549, 6.6, 35, 51, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada z prawdziwym 24 karatowym zlotem', 536, 6.6, 33.8, 57, 11.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada mleczna cytrusowa', 472, 4.6, 25.2, 55.3, 1.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada z okienkiem', 570, 8.5, 40, 44.5, 2.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada 70', 599, 7.8, 42.7, 45.8, 10.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czekolada 70 lacasa', 583, 6.1, 47.1, 33.6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('KostkaCzekolada 70 procent', 566, 9.5, 41, 34, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('KostkaCzekolada 77', 599, 7.8, 42.7, 45.8, 10.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('KostkaCzekolada 86 procent', 645, 8.5, 56.5, 18.5, 13, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('KostkaCzekolada 99', 590, 15, 51, 8, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('KostkaCzekolada cherry chili', 501, 6.2, 32, 43, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('KostkaCzekolada kokosowo orzechowej tiki taki', 538, 6.8, 35, 48.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czekolada Kostka1 6g jpg', 530, 6, 30, 58, 2.5, 0.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kostkagorzkiej Czekolada 64 proc', 502, 8.4, 31.8, 39.4, 12.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('dietetycznej Czekolada jogurtowej ritter sport', 497, 9, 37, 42, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Tabliczka Czekolada do wypiekow', 500, 5, 37.5, 55, 7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kawałek Czekolada bialej z calymi orzechami laskowymi', 560, 3.6, 37, 52.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Platkow owsianych gorskich', 366, 11.9, 7.2, 69.3, 6.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Platkow owsianych', 366, 11.9, 7.2, 69.3, 6.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Slonecznika w lupinach', 577, 28.8, 43.7, 18.6, 6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Slonecznik', 577, 28.8, 43.7, 18.6, 6, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Maki slonecznikowej', 391, 36, 19, 19, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Tunczyka w galarecie', 52, 8.2, 0.3, 3.2, 1.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Puszka tunczyka w Olej', 190, 27.1, 9, 0, 0, 1.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Tunczyka z wody', 110, 25.1, 0.9, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kawałek lososia wedzonego', 162, 21.5, 8.4, 0, 0, 3.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kakao', 459, 18.2, 21.7, 44.9, 5.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Pstrag wedzony', 117, 19.4, 4.4, 0.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pstrag swiezy', 160, 18.6, 9.6, 0, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Stek z halibuta', 186, 14, 14, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Udko z kurczaka', 159, 16.8, 10.2, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ugotowane udko z kurczaka', 136, 14.5, 8.8, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Wedzona noga z kurczaka', 156, 17, 9.7, 0.2, 0, 1.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Rzodkiewka', 18, 1, 0.2, 1.9, 2.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Biala rzodkiew', 14, 1, 0, 3, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pietruszka korzen', 49, 2.6, 0.5, 6.3, 4.2, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Natki pietruszki', 49, 4.4, 0.4, 4.8, 4.2, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Cukru', 405, 0, 0, 99.8, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Rzepa mini', 33, 1.1, 0.3, 4.7, 3.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czarna rzepa', 33, 1.1, 0.3, 4.7, 3.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej rydzowego', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z pestek wisni', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej z szarego maku', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej arganowego nierafinowanego', 822, 0, 92, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej kujawskiego czosnek i bazylia', 885, 0.6, 97.2, 1.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej', 884, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z pestek winogron', 828, 0, 92, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej arganowego', 893, 0, 99.2, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej kokosowe tloczonego na zimno', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej konopnego', 898, 0, 99.8, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej koperkowego', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej krokoszowego', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej kujawskiego 3 ziarna', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej kujawskiego czosnek i bazylia', 885, 0.6, 97.2, 1.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej makowego', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej migdalowego', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej sezamowego', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej slonecznikowego tloczonego na zimno', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z awokado', 884, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej z czarnuszki', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej z kielkow kukurydzy', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z kielkow pszenicy', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z lnianki', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z nasion pietruszki', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z ostropestu', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z pestek Arbuz', 900, 0, 100, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej z pestek czarnej porzeczki', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej z pestek moreli', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej z pestek winogron', 828, 0, 92, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Olej arganowego', 893, 0, 99.2, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej konopnego', 898, 0, 99.8, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Olej krokoszowego', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kalamarnicy w oliwie z oliwek', 173, 25, 7.8, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Poledwicy tunczyka z oliwa z oliwek', 86, 18, 1.5, 0, 0, 1.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Oliwy z oliwek', 882, 0, 99.6, 0.2, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Jajko sadzone', 245, 14.4, 20.8, 0.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jajko gotowane', 155, 12.6, 10.6, 1.1, 0, 0.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Jajo kurze', 140, 12.5, 9.7, 0.6, 0, 0.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Parowka drobiowa z cielecina sokoliki', 179, 14.5, 13, 1.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Parowka jedynka drobiowowieprzowa', 221, 13.3, 18.5, 0.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Parowka weganska soyami', 190, 11.1, 10.2, 12, 3.1, 1.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Parowka z indyka z serem', 226, 14.1, 18, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Parowka z szynki', 285, 13, 25, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Imbir', 80, 1.8, 0.7, 17.8, 2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Liofilizowanej kukurydzy', 381, 13, 4.5, 68, 8.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kolba kukurydzy', 115, 3.7, 1.5, 20.1, 3.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Soczewicy gotowanej na parze', 105, 8.5, 0.7, 14.1, 4.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Zoltej soczewicy', 459, 23, 1.4, 73, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Czarnej soczewicy', 334, 26, 1.9, 51.9, 8.9);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Zielonej soczewicy', 351, 24.2, 0.6, 60.8, 8.9);insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Prazonej ciecierzycy', 308, 15.5, 6, 10, 12, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Cieciorki konserwowej', 127, 6.3, 3.2, 18.3, 7.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ryż biały', 345, 7, 0.7, 76.5, 2.4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż do sushi', 343, 7.2, 0.5, 77.5, 2.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż dziki i parboiled', 360, 8.9, 1, 79, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż jaśminowy', 348, 6.8, 0.2, 80, 0.4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż parboiled bez gotowania', 356, 7, 1, 78, 4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż pelnoziarnistego', 344, 8, 2.2, 73, 3.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż risotto', 349, 7, 0.5, 79, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż tricolo', 344, 7.6, 1.4, 75, 1.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż dzikiego i parboiled', 360, 8.9, 1, 79, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż konjac', 6, 0, 0, 0.5, 4.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż parboiled bez gotowania', 356, 7, 1, 78, 4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż parboiled bez gotowania po przyrzadzeniu', 119, 2.3, 0.3, 26, 1.3);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Ryż risotto', 349, 7, 0.5, 79, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kaszanka', 195, 8.5, 12.6, 13, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kasza manny', 352, 9.5, 1.3, 74.2, 2.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza manna z truskawkami i platkami migdalow', 70, 3.2, 2.3, 10, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kaszanka wege', 200, 6.9, 11.2, 19.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza gryczana bez gotowania po przyrzadzeniu', 147, 5.8, 1.9, 23.8, 5.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza jaglana bez gotowania po przyrzadzeniu', 174, 5, 1.6, 33.6, 2.7);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza bulgur grysik', 360, 12.5, 1.8, 69, 8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza gryczana bez gotowania', 353, 14, 4.5, 57, 14);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza gryczana krakowskiej niepalonej', 340, 9.1, 1.7, 71, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza gryczana z warzywami', 307, 10.8, 2.6, 60.1, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza jaglana bez gotowania', 383, 11, 3.6, 74, 6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza jaglana preparowanej', 346, 10.5, 2.9, 71.6, 3.2);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza krolewskie', 354, 13, 4, 66, 6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza manny orkiszowej pelnoziarnistej', 346, 10.5, 1.5, 70.2, 5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza manny razowej', 348, 8.7, 1.3, 76.7, 4);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza orkiszowej', 384, 15, 2.4, 70, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza pszennej', 347, 14, 1.5, 66, 6.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Kasza z prazonego zielonego ziarna pszenicy freekeh', 360, 14, 2, 72, 12, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kaszanki wege', 200, 6.9, 11.2, 19.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Kasza bulgur', 360, 12.5, 1.8, 69, 8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Ananas', 55, 0.4, 0.2, 12.4, 1.2, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Pomarancza', 47, 0.9, 0.2, 9.4, 1.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Arbuz', 36, 0.6, 0.1, 8.1, 0.3, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Arbuz kandyzowanego', 348, 0.2, 0.2, 88, 0.4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Chleb zytni razowy', 227, 6.3, 1.7, 42.9, 8.4, 1.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Czerwonego wytrawnego wina', 68, 0.1, 0, 0.2, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Musztarda', 94, 3.9, 3.4, 9.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Musztarda kremskiej', 137, 4.7, 4.5, 15.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Musztarda miodowa', 147, 5.1, 4.9, 16.8, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Miód', 324, 0.3, 0, 79.5, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło', 735, 0.7, 82.5, 0.7, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło o obnizonej zawartosci cholesterolu o 87', 753, 0.4, 83.2, 0.7, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło bananowe', 92, 0.8, 3.8, 16, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło kokosowe', 643, 5.6, 62.8, 6.6, 21, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło orzechowe wzbogaconego bialkiem', 541, 33, 39, 9.2, 5, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło orzechowe z bananem', 565, 27, 41, 18, 8.9, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło orzechowe z wiorkami kokosowymi', 593, 23.2, 47.9, 15, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło ekstra 83 tluszczu', 751, 0.6, 83, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło z Mleko koziego', 770, 0.5, 85, 0.5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło kakaowe', 900, 0, 100, 0, 0, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło migdalowego', 628, 21, 52, 19, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło o smaku czosnku', 723, 0.3, 79, 3.4, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło o smaku szczypiorku', 739, 0.3, 81, 1.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło orzechowe 30 mniej tluszczu', 564, 18.7, 37.9, 34.6, 5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło orzechowe sante', 634, 26.6, 53, 8.5, 8.4, 0.8);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło orzechowe z kawalkami orzechow', 647, 21.7, 55, 13.4, 5.6);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło orzechowe z kawalkami orzechow rossmann', 635, 29, 52.3, 9.3, 0, 1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło z orzechow laskowych', 683, 14, 63, 15, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło z orzechow nerkowca', 591, 18.5, 46.5, 22.5, 7.5);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Masło z orzechow pecan', 758, 9.8, 74.3, 9.9, 5, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Masło z orzechow pistacjowych', 610, 21, 46, 28, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Mleko kozie w proszku', 479, 22.5, 28, 43, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage) values('Mleko 0%', 32, 3.2, 0, 4.7, 0);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Mleko 0.5%', 39, 3.4, 0.5, 5.1, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Mleko 1.5%', 47, 3.3, 1.5, 5, 0, 0.1);
insert into ingredient (name, kcal, protein, fat, carbohydrate, roughage, salt) values('Mleko 2%', 51, 3.3, 2, 4.9, 0, 0.1);
